### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by root-kalilinux** [hashXploiter/darkcoders-net#1]
Uncaught Error: Call to a member function fetchColumn() on bool in C:\xampp\htdocs\Panel\includes\config.php:50 Stack trace: #0 C:\xampp\htdocs\Panel\login\index.php(10): include() #1 {main} thrown in C:\xampp\htdocs\Panel\includes\config.php on line 50

**Comment by hashXploiter** [comment]
error fixed .download new database from the repo .
